# Generated by Django 6.0 on 2026-01-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ar', 'Arabic'), ('es', 'Spanish'), ('so', 'Somali'), ('ti', 'Tigrinya'), ('zh', 'Chinese'), ('ru', 'Russian'), ('ps', 'Pashto'), ('am', 'Amharic'), ('ps', 'Pashto'), ('ku', 'Kurdish'), ('fa', 'Farsi'), ('no', 'Norwegian')], default='en', max_length=5, verbose_name='Native Language'),
        ),
    ]
