# Generated by Django 6.0 on 2026-01-18 22:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemicAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom_category', models.CharField(max_length=100, verbose_name='Possible type of epidemic')),
                ('case_count', models.IntegerField(verbose_name='Number of cases detected')),
                ('time_window_hours', models.IntegerField(default=1, verbose_name='Within (hours)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Reviewed/Processed')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
