# Generated by Django 6.0 on 2026-01-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangerkeyword',
            name='word',
            field=models.CharField(max_length=100, unique=True, verbose_name='Det farlige ordet (norsk)'),
        ),
    ]
